language: python
python:
  - "2.7"
  - "2.7.3"
  - "2.7.4"
  - "2.7.5"
  - "2.7.6"
  - "2.7.7"
  - "2.7.8"
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install --upgrade pip"
  - "pip install .[dev]"
  - "pip install coveralls"
script:
  - nosetests
  - flake8
after_success:
  - coveralls
